### PR TITLE
User_interface branch pull request to Development branch 

### PR DESCRIPTION
**Pull request by henatan99**
This pull request is to merge user_interface branch to Development branch. user_interface code is written inside 'main' file considering the basic functionalities of the 'Ticktacktoe' game using gets, puts, print and iterators methods

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle: 

HELLO @zdrale  AND @henatan99  :wave:  VERY NICE PROGRESS SO FAR. YOU HAVE DONE A GOOD JOB, JUST A FEW CHANGES TO BE MADE KINDLY CHECK BELOW :arrow_down: 

- [ ] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken). KIndly create a board.

- [ ]  `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)

- [ ] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)

NB: You don't have to write the logic while creating the above steps.

- [ ] There are some unresolved rubocop errors. Kindly fix all the errors.
Screenshot from 2020-11-20 13-32-03



**if you have any question kindly reach me on slack** @peterrobert

### HAPPY CODING :computer:

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes  ♲
Hi, @zdrale and @henatan99, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE in this PR. 👏 You did very well on this project. ✨ I applaud you 👏👏👏 for accepting players' names.  Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] The game should ask the player to select from available moves (display occupied spots on the board)

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali ](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @henatan99 & @zdrale**

Great job with the project so far, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] you prompt the user for selecting a board size, even that the game can only support 3*3 beards. please make sure to remove that.

- [ ] the game should display a warning when a player selects an invalid move. right now it just quits. 

- [ ] the game should display the selected move inside the board without calculating the winning moves. right now the game displays an empty board.


### Optional 🟢 

- [ ] you can remove the games name prompt as it's not nessesary

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: :stop_sign: 
Hello team. Your game has been improved a lot. I can see that.:muscle:  But before moving on there are some changes that need to be done.

- [ ] Your game is accepting the repetitive inputs. I mean I choose 3 for x and in the next turn I choose 3 again and it just changes the symbol. Kindly fix this issue.
`[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)

- [ ] I am giving the mistake down there. The game just doesn't accept a valid move when I try to give. The number 1 was empty but I couldn't select it. 1 is not selectable on the board.
`[REQUIRED]` game asks the player to select from available moves
game

- [ ] You need to have winning conditions. I tried different winning conditions but in the end, the game does not end when the conditions were met.
`[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)

- [ ] Since I couldn't select every place in your board, I couldn't test the draw case but I am giving the necessary option that you have to take care of.
`[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)

This milestone is a bit tricky, I know. From the first look, it should go easy but unfortunately, it doesn't go smooth mostly. Take your time and kindly fix those issues. When you're ready please submit for a re-review. :100: 
If you have a question about the review, feel free to reach me via Slack. :100: 
Eyüp Sercan UYGUR

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
- Congratulations on the splendid job @zdrale! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
